### ISSUE TITLE
Validation of id-aa-ets-archiveTimestampv2 fails from version 1.70 onwards

### ISSUE THREAD

**Issue by zambonin** [bcgit/bc-java#1349]
Hello,

validating an archive timestamp (`id-aa-ets-archiveTimestampv2`, OID 1.2.840.113549.1.9.16.2.48) according to ETSI TS 101 733 V2.2.1 [1, Table K.3] in the context of a long-term signature worked until version 1.69. 

Starting from version 1.70, the validation fails and we suspect it's due to the `encapContentInfo` SEQUENCE being modified by the library, as in https://github.com/bcgit/bc-java/issues/1332#issuecomment-1460869863. For this specific attribute, the tag, length and value are all considered in the message imprint calculation, but the value unfortunately changes when using the `ContentInfo` or `CMSSignedData` classes to obtain the message bytes.

ETSI also recommends that the aforementioned SEQUENCE does not change in other parts of the standard, e.g. [1, Section 6.4.1, Note 3], as quoted below.

> Unless DER is used throughout, it is recommended that the binary encoding of the ASN.1 structures
being time-stamped be preserved when being archived to ensure that the recalculation of the data hash is
consistent.

[1] https://www.etsi.org/deliver/etsi_ts/101700_101799/101733/02.02.01_60/ts_101733v020201p.pdf

**Comment by dghgit** [comment]
Right... so yes, this is a bug... two bugs really, but one we clearly can't do anything about (hint, always DER if you're signing stuff...) The issue in the sample data was there was only a single octet string so the encoding was failing to preserve the constructed tag. I've fixed this. If you try 173b20 or later from https://www.bouncycastle.org/betas this should now be fixed. Let us know how you go.

**Comment by peterdettman** [comment]
@zambonin I still don't understand how re-encoding the encapContentInfo can affect a timetamp signature. The ETSI standard you reference seems clear that the input to the messageImprint hash includes the DER encoding of eContentType, as well as the actual eContent OCTET STRING (data, without any ASN.1 encoding structure), if present. That means you should explicitly DER-encode the eContentType for input to the signer, and for eContent, just pass getOctets().

**Comment by dghgit** [comment]
Another way of putting this, it might be useful to consider the 3 encodings:

308006092A864886F70D010701A0802480041F746573746520646520617373696E61747572612043414445532041442D5241000000000000
308006092a864886f70d010701a0802480040f746573746520646520617373696e610410747572612043414445532041442d5241000000000000
308006092a864886f70d010701a0802480040474657374040b6520646520617373696e610410747572612043414445532041442d5241000000000000

are all legitimate encodings of the same content info under BER but will all hash differently on their raw encodings. Unfortunately the opposite can also be done - as in different BER encodings can be constructed to hash to the same value. The consequence of this is that accepting BER makes it possible for people to construct other BER encodings which can be presented as the original item that was signed or hashed and you will not be able to tell when this has happened. This flexibility does not exist under the DER rules, and while I don't really know anything about the application concerned, I doubt this flexibility would be seen as a feature.

**Comment by zambonin** [comment]
To contextualize, we maintain the official digital signature validation tool of our country. While we do have a signer for testing, we cannot control how some services create their signatures and archive timestamps.

@peterdettman As far as I know, the `messageImprint` calculation procedure you're describing is that of the `id-aa-ets-longTermValidation` (OID 0.4.0.1733.2.2) attribute [1, p. 50], not ATSv2 [1, p. 45]. We have to support this specific attribute due to legacy reasons.

@dghgit Thanks for the fix! Our tests are passing again with 173b20. We will test more thoroughly and report in details next week, but it'll probably be fine.

**Comment by dghgit** [comment]
1.73 now published with the fix.
